import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import "@fortawesome/fontawesome-svg-core/styles.css";
import Providers from "./Provider";
import {Roboto } from 'next/font/google'
const roboto = Roboto({ 
  weight: ['400', '500', '700'], // BẮT BUỘC phải chọn weight đối với Roboto
  subsets: ['latin', 'vietnamese'], 
});
import "./globals.css";
import MainLayoutWrapper from "@/components/layout/MainLayout";
import { cookies } from "next/headers";
import { decodeTokenServer } from "@/helper/decodejwt";
async function getUserInfo() {
  const cookieStore = await cookies()
  const token = cookieStore.get('refreshToken')?.value
  const user = token ? decodeTokenServer(token) : null;
  return user;
  
}

export const metadata: Metadata = {
  title: "BMovie",
  description: "Generated by create next app",
  icons : [
    {
      url : '/icons/BMovie.svg',
      type: 'image/svg+xml'
    }
  ]
};
export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const user = await getUserInfo();
  return (
    <html
      lang="en">
      <body  className = {`${roboto.className}`}>
          <Providers>
                <MainLayoutWrapper user = {user}>{children}</MainLayoutWrapper>
          </Providers>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
