import type { Metadata } from "next";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Inter, Montserrat } from 'next/font/google'
const inter = Inter({ subsets: ['latin','vietnamese'], variable: '--font-inter' })
const montserrat = Montserrat({ subsets: ['latin','vietnamese'], variable: '--font-montserrat' })
import "./globals.css";
export const metadata: Metadata = {
  title: "BMovie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className={`${inter.variable} ${montserrat.variable} font-sans`} >{children}</body>
    </html>
  );
}
