import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/next';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Inter, Montserrat, Geist } from 'next/font/google'
const inter = Inter({ subsets: ['latin','vietnamese'], variable: '--font-inter' })
const montserrat = Montserrat({ subsets: ['latin','vietnamese'], variable: '--font-montserrat' })
import "./globals.css";
// import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "BMovie",
  description: "Generated by create next app",
  icons : [
    {
      url : '/icons/BMovie.svg',
      type: 'image/svg+xml'
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html
      lang="en">
      <body className={`${inter.variable} ${montserrat.variable} font-sans`} >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
